extensions:
  bearertokenauth:
    scheme: "Bearer"
    token: ${env:BEARER_TOKEN}
  
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  googlecloud:
    project: ${env:GOOGLE_CLOUD_PROJECT}
    log:
      default_log_name: claude-code-opentelemetry-collector
    
  googlemanagedprometheus:
    project: ${env:GOOGLE_CLOUD_PROJECT}

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 70
    spike_limit_percentage: 20

  batch:
    timeout: 10s
    send_batch_size: 1024
  
  resource/logs:
    attributes:
      - key: service.name
        value: "claude-code"
        action: insert

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: bearertokenauth

service:
  extensions: 
    - bearertokenauth
    - health_check
  
  pipelines:
    metrics:
      receivers: 
        - otlp
      processors: 
        - memory_limiter
        - batch
      exporters: 
        - googlemanagedprometheus
    
    logs:
      receivers: 
        - otlp
      processors: 
        - memory_limiter
        - resource/logs
        - batch
      exporters: 
        - googlecloud
